# Usa a imagem oficial do WordPress
FROM wordpress:latest

# Instala extensões PHP adicionais (opcional)
RUN docker-php-ext-install pdo pdo_mysql

# Define diretório de trabalho (opcional)
WORKDIR /var/www/html

# Exponha a porta padrão do Apache
EXPOSE 80
